development:
  adapter: postgresql
  encoding: unicode
  database: db_cinematographer_development
  pool: 5
  host: localhost
  username: Steven
  password: postgres_password

test:
  adapter: postgresql
  encoding: unicode
  database: db_cinematographer_test
  pool: 5
  username: Steven
  password: postgres_password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
